services:
  app:
    image: node:18-alpine
    command: sh -c 'yarn install && yarn run dev'
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      HOST: localhost
      PORT: 3000

      MYSQL_HOST: mysql
      MYSQL_USER: sample
      MYSQL_PASS: 1234
      MYSQL_DB: docker_test


  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - test-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: docker_test
      MYSQL_USER: sample
      MYSQL_PASSWORD: 1234

volumes:
  test-mysql-data:
